api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Go compiler distribution version"
  homepage = "https://github.com/paketo-buildpacks/go-dist"
  id = "paketo-buildpacks/go-dist"
  keywords = ["go", "distribution", "compiler"]
  name = "Paketo Buildpack for Go Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go-dist/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    go = "1.25.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:39042a078ea9ceebe3ecda4a7188f0f5b96e14a071d27923ba7f40b456e85ae3"
    cpe = "cpe:2.3:a:golang:go:1.25.13:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.13?checksum=39042a078ea9ceebe3ecda4a7188f0f5b96e14a071d27923ba7f40b456e85ae3&download_url=https://go.dev/dl/go1.25.13.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.25.13.src.tar.gz"
    source-checksum = "sha256:1d7e2f70b1ee9b93c7df8efcca71f5adcc6a59797a4336c2d10171bd4c174614"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.13.linux-amd64.tar.gz"
    version = "1.25.13"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:adad240fcb6bd180cf973b4b7c747baf4ec81d08b7d40ca35940ee4531971490"
    cpe = "cpe:2.3:a:golang:go:1.25.13:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.13?checksum=adad240fcb6bd180cf973b4b7c747baf4ec81d08b7d40ca35940ee4531971490&download_url=https://go.dev/dl/go1.25.13.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.25.13.src.tar.gz"
    source-checksum = "sha256:1d7e2f70b1ee9b93c7df8efcca71f5adcc6a59797a4336c2d10171bd4c174614"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.13.linux-arm64.tar.gz"
    version = "1.25.13"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:a21ae5633a269bcd7e90cf767e48225633795e99d831742cbf3397064fee7712"
    cpe = "cpe:2.3:a:golang:go:1.25.14:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.14?checksum=a21ae5633a269bcd7e90cf767e48225633795e99d831742cbf3397064fee7712&download_url=https://go.dev/dl/go1.25.14.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.25.14.src.tar.gz"
    source-checksum = "sha256:9e83f44f5fc297378861b4e16cc6aa114be8add7993fb3ceb2c512380aa4d582"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.14.linux-amd64.tar.gz"
    version = "1.25.14"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:9bf234ea70ffec9347fdf6b22ce4add51717d3386a38a441e8c8743fceb5eaee"
    cpe = "cpe:2.3:a:golang:go:1.25.14:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.14?checksum=9bf234ea70ffec9347fdf6b22ce4add51717d3386a38a441e8c8743fceb5eaee&download_url=https://go.dev/dl/go1.25.14.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.25.14.src.tar.gz"
    source-checksum = "sha256:9e83f44f5fc297378861b4e16cc6aa114be8add7993fb3ceb2c512380aa4d582"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.14.linux-arm64.tar.gz"
    version = "1.25.14"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:ffb5f8de10c62550dfddab66b36b57030721e0a44a3218e9e1181d7b59f121ca"
    cpe = "cpe:2.3:a:golang:go:1.26.7:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.7?checksum=ffb5f8de10c62550dfddab66b36b57030721e0a44a3218e9e1181d7b59f121ca&download_url=https://go.dev/dl/go1.26.7.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.26.7.src.tar.gz"
    source-checksum = "sha256:0ed24eac755105085b89fe9cabc2742b91a0ad7b94b59d3ad364918ebc8956ad"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.7.linux-amd64.tar.gz"
    version = "1.26.7"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:5a4ec883379d51ee9ce1040d5e87f8d35e20387574dd8c947feb01eabc3c1b37"
    cpe = "cpe:2.3:a:golang:go:1.26.7:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.7?checksum=5a4ec883379d51ee9ce1040d5e87f8d35e20387574dd8c947feb01eabc3c1b37&download_url=https://go.dev/dl/go1.26.7.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.26.7.src.tar.gz"
    source-checksum = "sha256:0ed24eac755105085b89fe9cabc2742b91a0ad7b94b59d3ad364918ebc8956ad"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.7.linux-arm64.tar.gz"
    version = "1.26.7"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:d0f743b33e8d8945e6b1f432edd15785c70507121d6e2a723b21285eddf8b57b"
    cpe = "cpe:2.3:a:golang:go:1.26.8:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.8?checksum=d0f743b33e8d8945e6b1f432edd15785c70507121d6e2a723b21285eddf8b57b&download_url=https://go.dev/dl/go1.26.8.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.26.8.src.tar.gz"
    source-checksum = "sha256:4e39b98e42f946fa05ac8bc5b71877df97dbdb7cbb1a777b541667ad7117fd2e"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.8.linux-amd64.tar.gz"
    version = "1.26.8"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:211ffced9dcb9633a55eac6364816ec0ddd951389a740e88fa8b3337971bdda0"
    cpe = "cpe:2.3:a:golang:go:1.26.8:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.8?checksum=211ffced9dcb9633a55eac6364816ec0ddd951389a740e88fa8b3337971bdda0&download_url=https://go.dev/dl/go1.26.8.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.26.8.src.tar.gz"
    source-checksum = "sha256:4e39b98e42f946fa05ac8bc5b71877df97dbdb7cbb1a777b541667ad7117fd2e"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.8.linux-arm64.tar.gz"
    version = "1.26.8"

  [[metadata.dependency-constraints]]
    constraint = "1.25.*"
    id = "go"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.26.*"
    id = "go"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
