api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Go compiler distribution version"
  homepage = "https://github.com/paketo-buildpacks/go-dist"
  id = "paketo-buildpacks/go-dist"
  keywords = ["go", "distribution", "compiler"]
  name = "Paketo Buildpack for Go Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go-dist/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    go = "1.25.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:ceb5e041bbc3893846bd1614d76cb4681c91dadee579426cf21a63f2d7e03be6"
    cpe = "cpe:2.3:a:golang:go:1.25.8:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.8?checksum=ceb5e041bbc3893846bd1614d76cb4681c91dadee579426cf21a63f2d7e03be6&download_url=https://go.dev/dl/go1.25.8.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.25.8.src.tar.gz"
    source-checksum = "sha256:e988d4a2446ac7fe3f6daa089a58e9936a52a381355adec1c8983230a8d6c59e"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.8.linux-amd64.tar.gz"
    version = "1.25.8"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:7d137f59f66bb93f40a6b2b11e713adc2a9d0c8d9ae581718e3fad19e5295dc7"
    cpe = "cpe:2.3:a:golang:go:1.25.8:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.8?checksum=7d137f59f66bb93f40a6b2b11e713adc2a9d0c8d9ae581718e3fad19e5295dc7&download_url=https://go.dev/dl/go1.25.8.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.25.8.src.tar.gz"
    source-checksum = "sha256:e988d4a2446ac7fe3f6daa089a58e9936a52a381355adec1c8983230a8d6c59e"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.8.linux-arm64.tar.gz"
    version = "1.25.8"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:00859d7bd6defe8bf84d9db9e57b9a4467b2887c18cd93ae7460e713db774bc1"
    cpe = "cpe:2.3:a:golang:go:1.25.9:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.9?checksum=00859d7bd6defe8bf84d9db9e57b9a4467b2887c18cd93ae7460e713db774bc1&download_url=https://go.dev/dl/go1.25.9.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.25.9.src.tar.gz"
    source-checksum = "sha256:0ec9ef8ebcea097aac37decae9f09a7218b451cd96be7d6ed513d8e4bcf909cf"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.9.linux-amd64.tar.gz"
    version = "1.25.9"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:ec342e7389b7f489564ed5463c63b16cf8040023dabc7861256677165a8c0e2b"
    cpe = "cpe:2.3:a:golang:go:1.25.9:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.9?checksum=ec342e7389b7f489564ed5463c63b16cf8040023dabc7861256677165a8c0e2b&download_url=https://go.dev/dl/go1.25.9.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.25.9.src.tar.gz"
    source-checksum = "sha256:0ec9ef8ebcea097aac37decae9f09a7218b451cd96be7d6ed513d8e4bcf909cf"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.9.linux-arm64.tar.gz"
    version = "1.25.9"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:031f088e5d955bab8657ede27ad4e3bc5b7c1ba281f05f245bcc304f327c987a"
    cpe = "cpe:2.3:a:golang:go:1.26.1:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.1?checksum=031f088e5d955bab8657ede27ad4e3bc5b7c1ba281f05f245bcc304f327c987a&download_url=https://go.dev/dl/go1.26.1.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.26.1.src.tar.gz"
    source-checksum = "sha256:3172293d04b209dc1144698e7ba13f0477f6ba8c5ffd0be66c20fdbc9785dfbb"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.1.linux-amd64.tar.gz"
    version = "1.26.1"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:a290581cfe4fe28ddd737dde3095f3dbeb7f2e4065cab4eae44dfc53b760c2f7"
    cpe = "cpe:2.3:a:golang:go:1.26.1:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.1?checksum=a290581cfe4fe28ddd737dde3095f3dbeb7f2e4065cab4eae44dfc53b760c2f7&download_url=https://go.dev/dl/go1.26.1.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.26.1.src.tar.gz"
    source-checksum = "sha256:3172293d04b209dc1144698e7ba13f0477f6ba8c5ffd0be66c20fdbc9785dfbb"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.1.linux-arm64.tar.gz"
    version = "1.26.1"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:990e6b4bbba816dc3ee129eaeaf4b42f17c2800b88a2166c265ac1a200262282"
    cpe = "cpe:2.3:a:golang:go:1.26.2:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.2?checksum=990e6b4bbba816dc3ee129eaeaf4b42f17c2800b88a2166c265ac1a200262282&download_url=https://go.dev/dl/go1.26.2.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.26.2.src.tar.gz"
    source-checksum = "sha256:2e91ebb6947a96e9436fb2b3926a8802efe63a6d375dffec4f82aa9dbd6fd43b"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.2.linux-amd64.tar.gz"
    version = "1.26.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:c958a1fe1b361391db163a485e21f5f228142d6f8b584f6bef89b26f66dc5b23"
    cpe = "cpe:2.3:a:golang:go:1.26.2:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.2?checksum=c958a1fe1b361391db163a485e21f5f228142d6f8b584f6bef89b26f66dc5b23&download_url=https://go.dev/dl/go1.26.2.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.26.2.src.tar.gz"
    source-checksum = "sha256:2e91ebb6947a96e9436fb2b3926a8802efe63a6d375dffec4f82aa9dbd6fd43b"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.2.linux-arm64.tar.gz"
    version = "1.26.2"

  [[metadata.dependency-constraints]]
    constraint = "1.25.*"
    id = "go"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.26.*"
    id = "go"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
