api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Go compiler distribution version"
  homepage = "https://github.com/paketo-buildpacks/go-dist"
  id = "paketo-buildpacks/go-dist"
  keywords = ["go", "distribution", "compiler"]
  name = "Paketo Buildpack for Go Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go-dist/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    go = "1.25.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:42d4f7a32316aa66591eca7e89867256057a4264451aca10570a715b3637ba70"
    cpe = "cpe:2.3:a:golang:go:1.25.10:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.10?checksum=42d4f7a32316aa66591eca7e89867256057a4264451aca10570a715b3637ba70&download_url=https://go.dev/dl/go1.25.10.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.25.10.src.tar.gz"
    source-checksum = "sha256:20cf04a92e5af99748e341bc8996fa28090c9ac98765fa115ec5ddf41d7af41d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.10.linux-amd64.tar.gz"
    version = "1.25.10"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:654da1f9b50a5d1c2a85ccf8ed405aa89c06e94d18384628bf186f7712677b08"
    cpe = "cpe:2.3:a:golang:go:1.25.10:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.10?checksum=654da1f9b50a5d1c2a85ccf8ed405aa89c06e94d18384628bf186f7712677b08&download_url=https://go.dev/dl/go1.25.10.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.25.10.src.tar.gz"
    source-checksum = "sha256:20cf04a92e5af99748e341bc8996fa28090c9ac98765fa115ec5ddf41d7af41d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.10.linux-arm64.tar.gz"
    version = "1.25.10"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:34f14304e856893f4ba30c2cacfe93906e9de7915c5f6aaaf3a81cdccd7ba30b"
    cpe = "cpe:2.3:a:golang:go:1.25.11:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.11?checksum=34f14304e856893f4ba30c2cacfe93906e9de7915c5f6aaaf3a81cdccd7ba30b&download_url=https://go.dev/dl/go1.25.11.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.25.11.src.tar.gz"
    source-checksum = "sha256:7b4e5b079b3c9bc420373ca68621a296b4d13c10735d4acac4171928d70f5480"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.11.linux-amd64.tar.gz"
    version = "1.25.11"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:c30bf9e156a54ea4e31fbbbf31a712b32734b58cc9a22426fa5ee632d0885124"
    cpe = "cpe:2.3:a:golang:go:1.25.11:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.25.11?checksum=c30bf9e156a54ea4e31fbbbf31a712b32734b58cc9a22426fa5ee632d0885124&download_url=https://go.dev/dl/go1.25.11.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.25.11.src.tar.gz"
    source-checksum = "sha256:7b4e5b079b3c9bc420373ca68621a296b4d13c10735d4acac4171928d70f5480"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.25.11.linux-arm64.tar.gz"
    version = "1.25.11"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:2b2cfc7148493da5e73981bffbf3353af381d5f93e789c82c79aff64962eb556"
    cpe = "cpe:2.3:a:golang:go:1.26.3:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.3?checksum=2b2cfc7148493da5e73981bffbf3353af381d5f93e789c82c79aff64962eb556&download_url=https://go.dev/dl/go1.26.3.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.26.3.src.tar.gz"
    source-checksum = "sha256:1c646875d0aa8799133184ed57cf79ff24bdefe8c8820470602a9d3d6d9192b8"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.3.linux-amd64.tar.gz"
    version = "1.26.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:9d89a3ea57d141c2b22d70083f2c8459ba3890f2d9e818e7e933b75614936565"
    cpe = "cpe:2.3:a:golang:go:1.26.3:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.3?checksum=9d89a3ea57d141c2b22d70083f2c8459ba3890f2d9e818e7e933b75614936565&download_url=https://go.dev/dl/go1.26.3.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.26.3.src.tar.gz"
    source-checksum = "sha256:1c646875d0aa8799133184ed57cf79ff24bdefe8c8820470602a9d3d6d9192b8"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.3.linux-arm64.tar.gz"
    version = "1.26.3"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:1153d3d50e0ac764b447adfe05c2bcf08e889d42a02e0fe0259bd47f6733ad7f"
    cpe = "cpe:2.3:a:golang:go:1.26.4:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.4?checksum=1153d3d50e0ac764b447adfe05c2bcf08e889d42a02e0fe0259bd47f6733ad7f&download_url=https://go.dev/dl/go1.26.4.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.26.4.src.tar.gz"
    source-checksum = "sha256:4f668a32fbfc1132e6a881fb968c2f1dada631492a339211735fbb255a42602d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.4.linux-amd64.tar.gz"
    version = "1.26.4"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:ef758ae7c6cf9267c9c0ef080b8965f453d89ab2d25d9eb22de4405925238768"
    cpe = "cpe:2.3:a:golang:go:1.26.4:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    os = "linux"
    purl = "pkg:generic/go@go1.26.4?checksum=ef758ae7c6cf9267c9c0ef080b8965f453d89ab2d25d9eb22de4405925238768&download_url=https://go.dev/dl/go1.26.4.linux-arm64.tar.gz"
    source = "https://go.dev/dl/go1.26.4.src.tar.gz"
    source-checksum = "sha256:4f668a32fbfc1132e6a881fb968c2f1dada631492a339211735fbb255a42602d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.26.4.linux-arm64.tar.gz"
    version = "1.26.4"

  [[metadata.dependency-constraints]]
    constraint = "1.25.*"
    id = "go"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.26.*"
    id = "go"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
