name: Set / Validate PR Labels
on:
  pull_request:
    branches:
    - main
    types:
    - synchronize
    - opened
    - reopened
    - labeled
    - unlabeled

jobs:
  autolabel:
    name: Semver Auto-Label
    runs-on: ubuntu-latest
    steps:
    - name: Auto-label Semver
      uses: paketo-buildpacks/github-config/actions/pull-request/auto-semver-label@main
      env:
        GITHUB_TOKEN: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

  validate:
    name: Ensure Minimal Semver Labels
    needs: autolabel
    runs-on: ubuntu-latest
    steps:
    - uses: mheap/github-action-required-labels@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        count: 1
        labels: semver:major, semver:minor, semver:patch
        mode: exactly
